### ISSUE TITLE
weitere User Wünsche für Version 1.2

### ISSUE THREAD

**Issue by CoolTuxNet** [LeonGaultier/fhem-AMAD#16]
<s>Handy Vibrieren lassen</s> ab Version 1.2 implementiert

Ab Version 1.2 implementiert
<s>Flugmodus aktivieren</s>
<s>Gerät runterfahren</s>

**Comment by hillbicks** [comment]
Hattest Du nochmal ueberlegt wie das mit dem Send Intent nachgedacht? :)

**Comment by CoolTuxNet** [comment]
Erklärt mal bitte noch mal kurz :-)

**Comment by hillbicks** [comment]
Also ich hab da grade auch nochmal drueber nachgedacht. 

SendBroadcast soll letztendlich wie openApp funktionieren, d.h. anstatt eine App zu starten soll die SendBroadcast Action in AM ausgefuehrt werden. Dafuer braucht es eigentlich gar nix neues in AMAD, ich denke openApp ist dafuer ausreichend. Den Rest kann man sich ja problemlos selbst zusammenbasteln.

Je laenger ich darueber nachdenke, desto sinnvoller erscheint es mir den openApp tree in dem SendCommand Flow in einen eigenen "App" auszulagern. Ich denke die meisten User werden Aenderungen an diesem Teil des Flows vornehmen. Bei einem Update muessen diese Aenderungen dann wieder nachgezogen werden. Da openApp aber ansich steht und es vermutlich keine Aenderungen an der Funktionalitaet mehr geben wird, koennte man den Baum doch in einen separaten auslagern, oder?

Was meinst Du dazu?

**Comment by hillbicks** [comment]
Nachtrag:

Ich hab grade mal den Baum aus SetCommand rauskopiert und in einen separaten gepackt, das funktioniert nachwievor wunderbar. 

Ich werde das bei mir auf jeden Fall so loesen das ich Aenderungen an openApp in einen extra Flow packe und dort auch die SendBroadcasts ausfuehre, und die ueber fhem dann per openApp antrigger. Dann brauch ich das bei der naechsten Version nicht alles neu machen und kann hier die Intents einbauen und Du brauchst auch kein extra Feature basteln das wir so nicht brauchen.

Der Intent/SendBroadcast ist ja letztendlich nichts anderes als openApp mit speziellen Parametern.

Aber ich denke das koennte auch fuer andere User besser sein das openApp als extra Flow zu haben.

**Comment by CoolTuxNet** [comment]
Für welche spezielle Anwendung benötigst Du das. Gib mal bitte ein Beispiel?
Es ist schwierig Teile die eigentlich ja in der Tat angepasst werden müssen aus zu lagern. Irgendwann hat man 6 Flows alleine nur für AMAD. Es sind jetzt ja schon 3, ohne ownReadings

**Comment by hillbicks** [comment]
Also erstmal speziell auf die apps bezogen. Du hast da ja schon eine Vorauswahl getroffen (gplay, tuneinradio), aber wenn ich stattdessen spotify und yatse nutzen will, dann muss ich den Flow jedes Mal bei einem Update vom SetCommand Flow wieder anpassen, auf mindestens zwei Geraeten. Wenn man mehr apps konfigurieren will, dann wird der Aufwand da noch hoeher. Ich denke das ist ein Szenario von dem die meisten/mehr User betroffen sind. 

Zusaetzlich habe ich noch zwei UseCases die ich umsetzen moechte:

1) Wenn ich das Mediacenter im Wohnzimmer starte, dann soll auf Telefon und Tablet die Fernbedienung yatse gestartet werden. Anschliessend will ich ein StartService in AM ausfuehren der den Host auf den im Wohnzimmer setzt und anschliessend die Library synchronisiert. Wenn ich das Mediacenter im Schlafzimmer starte, dann die gleiche Aktion nur eben mit einem anderen Host. Das laesst sich nur ueber Intents loesen.
http://yatse.leetzone.org/redmine/projects/androidwidget/wiki/Api

2) Wenn ich abwesend bin, dann soll auf den Wandtablets die MotionDetector App gestoppt werden (per intent) und anschliessend die IP Camera gestartet werden (ebenfalls per intent). Auch diese beiden Apps lassen sich per Intent kontrollieren und somit stoppen und starten. Nur die app zu starten ist nicht ausreichend. 

Ich kaempfe da momentan zwar noch mit AM, weil es sich da etwas anders verhaelt als Tasker, aber grundsaetzlich ist das moeglich und sind dann einfach Erweiterungen der jeweiligen App Baeume. Nachdem ich yatse gestartet habe, kommt eine weitere Action die auf den richtigen Host wechselt. 

Ich hoffe das wird so etwas klarer was ich vorhabe :)

**Comment by CoolTuxNet** [comment]
Jetzt beginne ich zu verstehen wo Du hin wilst.
Prinzipiell kann man in der Tat das ganze auslagern. Ich habe mir ja eh schon Gedanken zu userCommands gemacht. Soll rawSetCommands heißen. Da kann dann jeder seinen eigenen Command senden und den eigenen entsprechende. Flow ausführen lassen.

Bei openApp habe ich das Problem das ich den SetCommands Flow wo openApp drin ist ja noch gegen Fehler schütze. Es gibt zum Beispiel eine aktiv/inaktiv Fehlerbehandlung. Das wäre dann für den Flow openApp nicht mehr gegeben.
Aber  jetzt wo ich weiß wo Du hin willst, kann ich mir da mal Gedanken machen.
