### ISSUE TITLE
automagic Flow : translate messages in English ?

### ISSUE THREAD

**Issue by MalibuKoKo** [LeonGaultier/fhem-AMAD#25]
Some of the messages are in English and others in German, would it be possible to translate mostly in English?
Indeed, being French it is difficult to understand the different loops in automagic.

This could help the community to take the code and make it evolve, what do you think? I can help you...

**Comment by CoolTuxNet** [comment]
all information from trigger is in english, It is possible that some texts come from the action scripts. i will see that i can.

**Comment by CoolTuxNet** [comment]
media sektion is translate to english. thanks. do you have more sections found?
