### ISSUE TITLE
Start / Stop automagic Flows on a specific SSID ?

### ISSUE THREAD

**Issue by MalibuKoKo** [LeonGaultier/fhem-AMAD#26]
Is it possible to condition the execution of the "Information", "Send Data to AMADCommBridge" and "SetCommands" scripts when a mobile phone is connected to a specific SSID ?

This is to prevent these scripts from running outside my home and consuming the battery unnecessarily.

**Comment by CoolTuxNet** [comment]
is possible, you must set the attribut setAPSSID with multiple values separated by comma
