### ISSUE TITLE
Benachrichtigung in Statusbar: Automagic bei Android < 4.3 Abbruch

### ISSUE THREAD

**Issue by CoolTuxNet** [LeonGaultier/fhem-AMAD#7]
<s>Benachrichtigung in Statusbar: Automagic bringt eine Fehlermeldung mit Abbruch bei Android < 4.3.</s>

**Comment by CoolTuxNet** [comment]
Teilweise abgeschlossen. Ich habe es über eine Fehlerbehandlung im Flowablauf gelöst. In den nächsten Versionen kommt dann aber eine Versionsabfrage vom Android

**Comment by CoolTuxNet** [comment]
Warte auf die neue Version von Automagic, dort kann man dann eine Abfrage der SDK Version machen

**Comment by CoolTuxNet** [comment]
neue Version ist raus. Testimplementierung für Android Versionserkennung.
neues Reading "androidVersion"

**Comment by LeonGaultier** [comment]
Mit Version 1.0 umgesetzt
